### ISSUE TITLE
Where can we support development?

### ISSUE THREAD

**Issue by T0bycat** [ucupumar/ucupaint#101]
Is there anywhere where we can support the development or donate? This is a really cool plugin, and I want to see it grow even more!

**Comment by ucupumar** [comment]
I already have a Patreon page (https://www.patreon.com/ucupumar) but it is mostly for my model artworks. I haven't tried it yet, but maybe I'll create a sponsorship button on the GitHub repo if anyone wants to support the addon only.

**Comment by T0bycat** [comment]
I think that's a great idea!
