### ISSUE TITLE
Transition bump feature giving wrong normal direction

### ISSUE THREAD

**Issue by agnira** [ucupumar/ucupaint#110]
When I'm creating bump map layer with black (<0.5) value with transition bump feature, the layer is giving wrong normal direction. Check the example below.

Without transition bump:
![image](https://github.com/ucupumar/ucupaint/assets/67183228/58388228-aa6a-428c-ba9a-c81d2926d822)

With transition bump:
![image](https://github.com/ucupumar/ucupaint/assets/67183228/2e2e0b6c-f497-433b-a858-0a45b63c9d52)

**Comment by ucupumar** [comment]
It is intended behavior, since transition bump have its own settings for the height. If you want inverted/crease bump with transition bump, you need to enable flip in the the transition bump settings.
![image](https://github.com/ucupumar/ucupaint/assets/5253453/a1420c6a-fbf3-4421-97be-c1b6dd521bf2)
