### ISSUE TITLE
Mask offsets do nothing

### ISSUE THREAD

**Issue by Paul-Griffin-1517-1** [ucupumar/ucupaint#113]
(Blender 4.1, Ucupaint Branch Stable 1.2.5)

Offsets for masks do nothing.
To replicate:
Add a solid color, give it a gradient/checker/etc as a mask. Adjusting the offset/rotation/scale does nothing. Adjusting the controls within the actual shader works as expected.
This seems to happen with all mask types, including hand-painted ones.

Offsets for other uses (such as "color input") seem to work as expected.

**Comment by ucupumar** [comment]
This issue is already fixed in the master and it will be included in 1.2.6.

**Comment by Paul-Griffin-1517-1** [comment]
Oh wonderful! Apologies, didn't realize that.
