### ISSUE TITLE
Images cannot be saved

### ISSUE THREAD

**Issue by iillya** [ucupumar/ucupaint#116]
blender 4.1
ucupaint 1.2.7
An error is reported when saving an image.
<img width="1280" alt="Snipaste_2024-05-30_19-44-14" src="https://github.com/ucupumar/ucupaint/assets/112866800/2e23edd0-5c16-4251-831e-1f89c0a4aa3a">

**Comment by ucupumar** [comment]
Thanks for the report, yeah I can confirm this is also happening here. I'll try to fix it later.
