### ISSUE TITLE
Texture interpolation options when creating a new layer.

### ISSUE THREAD

**Issue by Maba0** [ucupumar/ucupaint#118]
Hello I really like this addon. I am now able to handpaint my lowpoly models in blender which is awesome!
Most of the time I'm texturing at low resolutions and prefer the texture interpolation mode to be set for closest.
The work around is every time I create a new layer I need to go into the nodegroup and switch the interpolation
mode to closest.

I am requesting that when creating a new layer there is an option to choose which interpolation mode to use.

Thank you!

**Comment by ucupumar** [comment]
You probably shouldn't edit the inside of the node group yourself. There's already an option in the ucupaint to change the texture filtering, albeit not in the new layer option tho.
![image](https://github.com/ucupumar/ucupaint/assets/5253453/c21427d4-015b-4e49-be21-c05c43c90118)
