### ISSUE TITLE
Whether UV can be loaded automatically

### ISSUE THREAD

**Issue by sangouzhi** [ucupumar/ucupaint#120]
![微信图片_20240605233058](https://github.com/ucupumar/ucupaint/assets/114461992/c5af4074-21d8-4fea-9fd0-5d2262f9fb9e)

**Comment by ucupumar** [comment]
Can you explain a little bit more what do you mean here?

**Comment by sangouzhi** [comment]
> 你能进一步解释一下这里的意思吗？

Sorry, I processed on your plugin, which caused the problem. Sorry
