### ISSUE TITLE
Material disappears in solid view

### ISSUE THREAD

**Issue by zokadev-mc** [ucupumar/ucupaint#131]
When I am on a new image layer in the solid view with the texture, all my material disappears except the texture I am painting over, is there any way to make what is not part of the texture visible in this solid view?
![Blender](https://github.com/ucupumar/ucupaint/assets/140729730/b54d1f6f-844b-440d-ad63-3f03698729d3)

**Comment by ucupumar** [comment]
It's just what solid view does in blender, it can only display one image at a time. Ucupaint is a material node setup, so you need to be on material or rendered view to see the actual material result.

**Comment by zokadev-mc** [comment]
Ooooh all right tysm ^^
