### ISSUE TITLE
Erase alpha icon feature doesn't work

### ISSUE THREAD

**Issue by don570** [ucupumar/ucupaint#136]
version 129 - linux blender 4.1.1
Erase alpha icon feature doesn't work

When I am using a brush I can change the mode from 'MIX' to 'Erase alpha'
at the top of blender window and it works properly.  Then I can change back to MIX mode 
using the menu again.

However when I click the red icon in ucupaint to disable  'Erase alpha' mode
it is ignored

**Comment by ucupumar** [comment]
I just tried the toggle eraser button and it works fine here. To make it clear, can you give a video example of how to reproduce the issue?

**Comment by don570** [comment]
I didn't explain clearly.  The Toggle Eraser feature works well.

It's the 'Disable Eraser'  icon that doesn't seem to be working (or I do not understand it properly)
Procedure to explain problem...

1.  Starting with a default cube and no material
2. launch ucupaint and create solid color layer with a mask.
3. I check that the mask is working properly i.e  white paints the solid color and black erases

4. I changed from 'Mix' to 'Erase alpha' mode

'Disable Eraser'  icon appears in ucupaint panel

5. Clicking on 'Disable Eraser' icon switches the brush color between white and black
but the brush doesn't paint in blender window.   So I am confused.  What does 'Disable Eraser' do?

6. If I change back to 'Mix' mode then the brush works again
i.e  white paints the solid color and black erases

If I change back to 'Mix' mode then the bush works again

________________________________

**Comment by ucupumar** [comment]
I see. Disable eraser button is only shown when you're using erase alpha while painting mask, since it makes sense to only use grayscale brush when painting mask. I'll change the behavior of the button to only show if you actually use the brush created by using toggle eraser rather than manually change the brush blend mode to erase alpha.
