### ISSUE TITLE
Toggle Eraser in Erase Alpha mode

### ISSUE THREAD

**Issue by don570** [ucupumar/ucupaint#137]
I believe I found a situation when the Toggle Eraser button doesn't work.
It's not very serious since it only occurs in a special situation.

Procedure

1. Start with default cube . Green is background
2. Create first layer.  --->  Open images to single layer
3. Brush works correctly in mix mode
4. Switch to Erase alpha mode  and the Toggle Eraser button doesn't toggle
5. I go back to mix mode and the Toggle Eraser button now seems to work properly

I have made a short video to demonstrate the procedure...
https://drive.google.com/file/d/1EwQi7RwDyzqKy0RnUiev2WToBI1NMQ-w/view?usp=sharing

**Comment by ucupumar** [comment]
Toggle eraser is just a toggle to switch your current brush to a custom eraser brush ucupaint created. You still need to make sure your current brush is not an eraser brush by itself. This is a non-issue, sorry, I'm closing this one.
