### ISSUE TITLE
Add option to use non color for custom bake target image

### ISSUE THREAD

**Issue by ucupumar** [ucupumar/ucupaint#140]
Sometimes blender displays a wrong value on srgb image as reported by discord user, Non-color image can be a fix for that. 
![image](https://github.com/ucupumar/ucupaint/assets/5253453/fd95b709-8b0a-4454-8aac-65e3a6d4e92b)
![image](https://github.com/ucupumar/ucupaint/assets/5253453/811ea67a-e6f6-4c35-831c-d7feed63929c)

**Comment by AndyLobjois** [comment]
If I may, perhaps it's a Blender bug but I'll assume sRGB will not bother displaying RGB values if they are not visible from Alpha. So I'm assuming it work as intended.

Anyway for my case here, the baked texture is by default in sRGB.
It could be great to choose the color space in the Custom Bake Targets menu.

**Comment by ucupumar** [comment]
I see. Yeah, I think it's better to have a colorspace option when creating a new custom bake image.

**Comment by AndyLobjois** [comment]
Blender file example of the situation : [Ucupaint Test - Bake Color Space sRGB to Non-Color.blend](https://github.com/user-attachments/files/16179409/Ucupaint.Test.-.Bake.Color.Space.sRGB.to.Non-Color.zip)

Open the blend file and press Bake All Textures.
Then check the texture named "BAKE" in Image Editor, in the View sidebar tab, you can see it's in sRGB.

**Comment by ucupumar** [comment]
I just tried the file and the bake result is already visible after baking.
![image](https://github.com/user-attachments/assets/4f20a3eb-c71a-4299-8e62-f866be2f8d03)
Are you sure you're not having the same result? What GPU are you using?

**Comment by AndyLobjois** [comment]
It's not the result I expect, and as you can see the image is in sRGB color space.
And when you switch to "Non-Color" (after saving), you should get that:
![image](https://github.com/user-attachments/assets/8dac7e05-d66c-42b0-974a-abe439d9f637)

**Comment by ucupumar** [comment]
Sorry for the late update. I already made a commit to make custom bake target images to always use Non-color instead. I don't think there are any use cases of custom bake targets with srgb color.
