### ISSUE TITLE
New Image  Layer can't be removed

### ISSUE THREAD

**Issue by don570** [ucupumar/ucupaint#143]
BLender 4.2 LTS  linux
Only occurs in Ucupaint version 2.0.1

New Image  Layer can't be removed. I click on minus icon to remove layer and 
I get error message (attachment)
A solid color layer doesn't have this problem.
Undo operation Ctrl-Z  sets everything to working order.
![xscreenshot-20240726T012640](https://github.com/user-attachments/assets/305de414-6a10-4a7b-87d2-fc2ebe43f3fe)

**Comment by ucupumar** [comment]
Hmm, are you sure you're already reloading the script or restating your blender? Because the error doesn't seem to make sense.

**Comment by don570** [comment]
When I restarted my Bender 4.2 the problem went away,
so it was some residual code in memory.

I tested  version 2.0.1 and bevel grayscale and bevel normal work well.

**Comment by ucupumar** [comment]
Okay, maybe extension platform does not fully reload the code after updating. I'm closing this issue then.
