### ISSUE TITLE
When an object has multiple materials, there is an error in  baking AO or other things.

### ISSUE THREAD

**Issue by iillya** [ucupumar/ucupaint#15]
Same situation as last time.When I bake the AO  of the body part, it affects the texture of the face.The same goes for others like cavity.

<img width="1707" alt="Snipaste_2023-07-31_15-24-19" src="https://github.com/ucupumar/ucupaint/assets/112866800/aaa0866e-9a81-408d-9bf0-eecc6411de43">
<img width="437" alt="Snipaste_2023-07-31_15-25-55" src="https://github.com/ucupumar/ucupaint/assets/112866800/2a6dd4e5-8990-40a3-bf66-af33285232a9">

**Comment by ucupumar** [comment]
Can you provide an example blend file?

**Comment by iillya** [comment]
> Can you provide an example blend file?

[untitled.zip](https://github.com/ucupumar/ucupaint/files/12212860/untitled.zip)
