### ISSUE TITLE
Color alpha cannot be overwritten

### ISSUE THREAD

**Issue by muhuk** [ucupumar/ucupaint#150]
![image](https://github.com/user-attachments/assets/4b14e80d-7259-485b-9293-4a42621066fb)

Alpha of colors doesn't seem to affect final color alpha no matter what. Adding a float channel connected to alpha works. But then why is there an option for color alpha in the first place? More importantly; why am I able to set alpha on the layer's color? (If I use a color override and hide and unhide the channel, the override's color is set to `1.0`, but the alpha of the layer's color is maintained.)

[ucupaint_color_alpha.zip](https://github.com/user-attachments/files/16506658/ucupaint_color_alpha.zip)

**Comment by ucupumar** [comment]
This is the limitation of blender node system, eventhough you can change the alpha of the color input, the value won't actually be read. This is one of the reasons there's a need for a dedicated alpha toggle on the main channel. And currently there's no way to make the input only show the rgb without alpha.
