### ISSUE TITLE
Cannot use alpha from alpha texture

### ISSUE THREAD

**Issue by muhuk** [ucupumar/ucupaint#151]
When I bake other object's channels, alpha gets messed up. It seems the alpha texture's color is influencing the alpha, but not its alpha (which is baked perfectly fine). I couldn't figure out a way to use the alpha channel using modifiers.

Using Blender 4.2, Ucupaint 2.0.1.

[ucupaint_alpha_texture.zip](https://github.com/user-attachments/files/16506976/ucupaint_alpha_texture.zip)

**Comment by ucupumar** [comment]
Rather than creating dedicated alpha channel manually, you can just enable alpha on your color channel, it will use 0.0 by default so the background color will be transparent.
![image](https://github.com/user-attachments/assets/f1632980-f7e7-4f21-ada7-7138f18c0cf4)

**Comment by muhuk** [comment]
But then I can't modify alpha further, can I? See #150

**Comment by ucupumar** [comment]
You can use background layer for that. This is the example of how you can use it https://x.com/ucupaint/status/1792134005548274044
