### ISSUE TITLE
Making a bump map is broken

### ISSUE THREAD

**Issue by starsiderfox** [ucupumar/ucupaint#158]
Just try to add a layer affecting normal in bump map mode. Either in the adding image menu or in the channels panel of the layer. It gives me this error in Blender 4.0, 4.1 and 4.2. Ucupaint 2.0.1.

```
  File "/home/user/.config/blender/4.1/scripts/addons/ucupaint/node_connections.py", line 2838, in reconnect_layer_nodes
    if prev_max_height: create_link(tree, prev_max_height, max_height_calc.inputs['Prev Bump Distance'])
                                                           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'bpy_prop_collection[key]: key "Prev Bump Distance" not found'
```

Using Linux but I think it would happen in any OS.

**Comment by ucupumar** [comment]
Can you try the latest master commit of ucupaint? The code already changes a lot since 2.0.1 release

**Comment by don570** [comment]
Latest version from github worked well for me.
I tried a normal channel and then tried displacement modifier on selected vertices.
Both the normal bumping and the displacement displayed simultanelously on different parts of object.
Worked in EEVEE and cycles rendering

**Comment by ucupumar** [comment]
Thanks for the report! Sorry for the late reply, I'll release a new version probably early next month. I'll check again about this issue soon just to make sure it is actually fixed.

**Comment by ucupumar** [comment]
Ok, I already checked this twice, I think this problem actually really solved
