### ISSUE TITLE
Fake lighting option with Bake All Channels

### ISSUE THREAD

**Issue by don570** [ucupumar/ucupaint#164]
I downloaded Sunday git version of ucupaint
Blender 4.2.1 linux version

Method :  I started with a plane 
-subdivided a few times
-poke faces command to make a 3d pattern on the plane (see image)

Using ucupaint I made a layer with two channels --> color and normal
With fake lighting mask  I was able to make a useful displacement image. (see image for displacement image)
However when the fake lightning mask isn't used the displacement image is not useful
This got me thinking.

Would it be useful to have a Fake lighting option when the  ' Bake All Channels' dialog window is shown?
Normally it would be unticked, but in special situations like a plane which has a rough pattern  ,  it could be ticked ON .
Ucucpaint could then assume some useful angle of fake lightning (such as 25 degrees from normal)  and  output a useful displacement image.

Alternative proposal  -  I would advise some pop-up help text to advise users how to use Fake Lighting
like  'Show 3-D pattern on a plane'
.
![ucupaint-fake-lighting](https://github.com/user-attachments/assets/58922e61-1750-4fc2-aef8-72301333901b)

**Comment by ucupumar** [comment]
I'm sorry, but I'm unsure if I can understand what you meant here. Can you give some video examples or something?

**Comment by don570** [comment]
I spent time learning the Fake Lightning feature 
Download Fake Lighting video
https://youtu.be/wcbng3vdVd8

Here is summary that I have learned:

1) the layer needs  two channels set up  -->   color and normal
2) The normal channel should choose 'Bump' rather than 'Bump + Normal' 
3)  There is two places that 'Fake Lighting' can be chosen   --->   Layer and Channel
However I can only get the correct  displacement image if I choose the channel's  Fake Lighting' option
4) 'World' must be chosen for 'Fake Lighting' ,   otherwise displacement image is worthless
5) Setting an angle for the Fake Lighting affects the output
6) If I don't make the setting correctly then  the displacement image uses the EXR format rather than PNG

So I suggest that wiki page explain why 'Fake Lighting ' gives a different effect depending on whether
the Layer window is used or the channel  menu list is used for the selection.

**Comment by ucupumar** [comment]
I just made a change to make fake lighting contribute to normal channel baking. Please use the latest master branch to try it. Thanks for the report!
