### ISSUE TITLE
Baked normal maps not exporting to 16bit TIFF

### ISSUE THREAD

**Issue by trashmaster9000** [ucupumar/ucupaint#165]
hi!
i discovered that normal maps are not exported as 16bit tiff when i save them externally after baking.
if i export the image as 16bit png first and then export it as 16bit tiff its exporting correctly

would be nice if you could have a look at it!

**Comment by ucupumar** [comment]
Thanks for the report! I already tested this and I think this problem is caused by Blender not being able to save 16-bit TIFF when the image uses 8-bit color. Maybe there should be a way to bake normal to float image to fix this issue.

**Comment by trashmaster9000** [comment]
ok, so i tried something:

if i do "Bake all", go to the image editor, discard the baked image which lets me manually enable "Float buffer", bake again and save it as 16bit tiff its working as it should be.

maybe you could just add a "Float buffer" checkbox to the "new bake target" dialogue or simply mark normals as float buffer by default?

**Comment by ucupumar** [comment]
I just added the option to bake normal to float image but it's disabled by default, I already tested it with a TIFF image and it worked fine. Thanks for the report! 👍
![image](https://github.com/user-attachments/assets/f87fdb10-60c4-41d9-94e7-3ca3040f55d0)

**Comment by ucupumar** [comment]
Oh, I forgot about custom bake target, I just added an option to use float with custom bake target
