### ISSUE TITLE
Discord Server Invites are no more valid

### ISSUE THREAD

**Issue by Leevy27** [ucupumar/ucupaint#166]
Just to let you know, that every Discord links are invalid and unable to accept invites

**Comment by ucupumar** [comment]
Hmm, that's weird, I already saw you on the server
![image](https://github.com/user-attachments/assets/323fd0ff-05af-4cb6-98bb-6444c24db3bc)

What kind of message did you get on discord?

**Comment by Leevy27** [comment]
Hi,

look at the image attached.

**Comment by Leevy27** [comment]
![image](https://github.com/user-attachments/assets/9435c57a-ab19-4e0e-a4ed-892f0355dd47)

**Comment by ucupumar** [comment]
Which link did you use?

**Comment by Leevy27** [comment]
Almost all I found on Google!

https://discord.gg/BdNfGGzQHh

Even the link here on your GitHub (Readme) is not working

**Comment by ucupumar** [comment]
I still see new members since you posted this issue, I'm not sure what happened in your place, but try to update your discord or maybe use a different account.

**Comment by Leevy27** [comment]
I managed now to connect the server. Thank you
