### ISSUE TITLE
Bug: "Open Material Images to Layer" Asset Browser functionality scans unrelated files

### ISSUE THREAD

**Issue by eisegesis-623** [ucupumar/ucupaint#168]
I've been attempting to use the new "Open Material Images to Layer" functionality for the Asset Browser in Ucupaint 2.1.0 in blender 4.2.0 Stable.

Step by step, here is what I am doing and what is occurring.

- I create a Quick Ucupaint Node Setup
- I select a material in the asset browser, press W, and click "Open Material Images to Layer." I press OK on the following popup.
- Blender freezes for a few moments before producing the following error: 
- `Python: Traceback (most recent call last):
  File "C:\Users\pauly\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\blender_org\ucupaint\Layer.py", line 2131, in execute
    with bpy.data.libraries.load(str(blend_file), assets_only=True) as (data_from, data_to):
OSError: load: myfilepath\myblenderfile.blend failed to open blend file`
- Between 1 and 2 copies of the material datablock are added to the current .blend file. Each copy's datablock is tagged as an asset. No layers are added to the Ucupaint material's layer stack. This occurs even if the material has no images and would normally trigger the "no images found in material" error.
- If the material datablock copy(ies) are left in the file, "Open Material Images to Layer" behaves as expected. Blender does not freeze and the images are added to the layer stack. However, removing those datablocks causes the previously described behavior.

What seems to be happening with the error message is that Ucupaint (or the asset browser) is, for some reason, scanning every .blend file in every folder/subfolders of every asset library, regardless of whether the .blend has an asset in it or if the selected material asset is even in that library. If any .blend files in any of these folders are corrupted, Blender will return an error and the functionality will break. Additionally, if the material is present in the file already the scan will not occur and there will be no errors (as demonstrated by the behavior with the "copies" caused by the error).

**Comment by ucupumar** [comment]
Can you try it again with the latest master commit? This issue is possibly already fixed

**Comment by ucupumar** [comment]
Op didn't respond but I'm pretty sure this one already fixed

**Comment by eisegesis-623** [comment]
Apologies for not responding, I didn't see a notification :( but yes it appears to be fixed now. Thank you so much!
