### ISSUE TITLE
Make image packing/unpacking functionality clearer, protect against saving over images used externally

### ISSUE THREAD

**Issue by FairlySadPanda** [ucupumar/ucupaint#172]
I've had a lot of trouble trying to stop Ucupaint from accidentally saving over a file I'm actually using in my game editor.

Sometimes a layer or a baked image ends up referencing the same file my game editor is using for a material, and when that layer is saved or modified on Blender's side, it writes to a file I don't want changed.

I think that packing/unpacking images is really unclear in what it does and why you should/should not have an image packed. I didn't find clear guidance online.

Likewise baking a file often is to support getting the result of my work out into my game editor. The problem is that if I need to re-bake this file, and I saved directly into my game editor's asset folder, the re-bake can update the file even if I'm trying to create a new variant of a material.

This all means I have to make a special folder just to place all my Ucupaint work and then manually copy out stuff I've made from that folder into where I want to use it.

I'd like Ucupaint to either have an option to, or default to, not overwriting an external texture file unless the user is aware of what file is being overwritten where, and when baking a texture to be able to specify the name of the baked file and where it'll go in the bake pop-up window, so the user can choose to overwrite an old file or make a new one.

**Comment by ucupumar** [comment]
Packed means the images are packed inside the blend file so that it won't mess with your external files. There's `Copy` option when you're doing a `Save as Image` in blender so your saved images won't be used as the image source.
![image](https://github.com/user-attachments/assets/c6b347cc-3bff-450f-be09-3ff8753c31ae)

The option is only available for standard `Save as Image` operator though. I still need to add `Copy` option to `Save all baked images` operator

**Comment by FairlySadPanda** [comment]
Thanks; this information would be good to have in the documentation.

**Comment by ucupumar** [comment]
I just added a menu listing for easier to save an image copy. It can be accessed here for standard image
![image](https://github.com/user-attachments/assets/603d8660-ea74-4b65-91fd-1e9cb02439f4)
Or here for quickly save all baked channel image copies
![image](https://github.com/user-attachments/assets/20032829-b2a7-4857-80fe-26a5d4270cef)
