### ISSUE TITLE
Bake a set of layers on top of transparency or a background colour

### ISSUE THREAD

**Issue by FairlySadPanda** [ucupumar/ucupaint#173]
It's currently not easy to figure out, or not possible, to just select, say, five layers out of fifty and do a bake of only those layers. 

An example of this in use would be:

1. Make a nice base mesh texture via a few Ucupaint layers.
2. Paint a nice decal or detail texture on it
3. Bake that decal or detail texture to a transparent file
4. Slap the new texture as a layer on a material in a game engine.

See also: creating masks out of multiple layers of transparency editing.

What I found trying to do this via toggling visibility of layers before baking was either that I'd end up baking onto whatever my model's base texture information was, bake onto shader pink, or bake onto black/white representing the unpainted bits of the model on those layers. I ended up having to save all the layers I wanted individually then combine them in an image editor.

**Comment by ucupumar** [comment]
Bake layer as image(s) is already in the todo list (#65), so when it's already implemented, you can bake the inside of a layer group into images then you can save it to disk. So this issue can be resolved if #65 is implemented, so I'm closing this issue as a duplicate.
