### ISSUE TITLE
Missing UI after using image alpha as mask

### ISSUE THREAD

**Issue by daxime** [ucupumar/ucupaint#188]
Hi,
I'm learning to use this awesome addon by watching a tutorial on how to use this addon and towards the end of the tutorial, you have to reproduce details (transparency) present on another layer. Except that he didn't use a mask, and I didn't either.

I looked to see if it's possible to create a mask based on the alpha of a layer, but I couldn't find anything. I won't make this mistake again, but I thought it would be a good idea to add this possibility to the addon.

**Comment by ucupumar** [comment]
You can already use image alpha as mask input. Is this what you meant?
![image](https://github.com/user-attachments/assets/3303e5ec-8e88-4712-8810-b1d32b19cf35)

**Comment by daxime** [comment]
Yes, exactly. Thx
It work but the interface is weird. 

Here i want to apply the alpha of "Green Paint" on "Yellow radiation"
![Capture d’écran du 2024-10-12 14-22-11](https://github.com/user-attachments/assets/d13c95bb-415e-4dbd-ae50-6a87cb50eede)

The result work, but the layer label is blank, and all the setting for the mask is empty. 
![Capture d’écran du 2024-10-12 14-22-38](https://github.com/user-attachments/assets/a19fd2bf-11da-4847-9d67-8cb474c47e0f)

**Comment by ucupumar** [comment]
I see, it's probably a bug, can you upload the sample file so I can check it?

**Comment by daxime** [comment]
Here is file:
https://mega.nz/file/ftxBCYoD#qIdySWnhT3v14x9Is3J0Hk_2eQmcp7Y4b6V2JqbU4Kk

**Comment by ucupumar** [comment]
Okay, just tested your file and yeah it's a bug. I renamed this issue with the related problem.

**Comment by ucupumar** [comment]
I just fixed the issue, please use the latest master branch to test it

**Comment by daxime** [comment]
Perfect, thx for your help :)
