### ISSUE TITLE
Trying to bake Fake Lighting throws an error when it's used in certain layer stacks

### ISSUE THREAD

**Issue by passivestar** [ucupumar/ucupaint#191]
Bakes fine on its own but throws an error when a layer with Fake Lighting is used in a stack with a PBR layer

https://github.com/user-attachments/assets/010e9c39-761a-4602-b1a4-1e73e8f47aae

**Comment by ucupumar** [comment]
I can't seem to reproduce the error here, maybe it's just because I don't follow the exact steps like you did. Can you upload the sample file?

**Comment by ucupumar** [comment]
Ok, I can reproduce it here, the problem is because of the fake lighting mask modifier
