### ISSUE TITLE
Incorrect image paths if the blend file is saved after images were imported to ucupaint

### ISSUE THREAD

**Issue by passivestar** [ucupumar/ucupaint#192]
Paths have the path of the blend file directory + the full path to the texture file in them, so trying to pack them fails

This only happens if the blend file is saved AFTER "Open Material Images to Layer" is used. If the blend file is saved first and "Open Material Images to Layer" is used afterwards it works fine

https://github.com/user-attachments/assets/b8d766f2-a38a-45d3-a33e-36cc64b251e1

**Comment by ucupumar** [comment]
Hmm, I can't reproduce this on a Windows machine. Ucupaint always uses a relative path by default, does this kind of thing cause problems in Mac?

**Comment by passivestar** [comment]
> does this kind of thing usually cause problems in Mac?

not really, no

> Ucupaint always uses a relative path by default

what would the path be relative to when the blend file isn't saved? it can only be absolute in that case, right? 🤔

**Comment by ucupumar** [comment]
Yeah, it will use the default value when it's impossible to use the relative path, the code is in Layer.py in this line
![image](https://github.com/user-attachments/assets/2d737d0a-a047-4739-af51-4d2ae50b49d8)
I just used try catch like that.
