### ISSUE TITLE
Add a warning popup when trying to merge layers with unsaved images

### ISSUE THREAD

**Issue by passivestar** [ucupumar/ucupaint#193]
Trying to merge and then undo with Ctrl+Z results in a loss of data. Merge should probably check if we're trying to merge layers that have unsaved images and show a warning

https://github.com/user-attachments/assets/373c8ee7-8278-45e5-826f-399180d4898d

**Comment by ucupumar** [comment]
Merging layers most of the time is always destructive in blender afaik. I'm not sure if this one is possible to fix

**Comment by passivestar** [comment]
Undo works if the images are saved though (if the blend file is saved). So it could just check if the images are saved and show a warning that it can't be undone if they aren't

**Comment by ucupumar** [comment]
Okay, I'll change the title of the issue then
