### ISSUE TITLE
AO baking has different behavior - shared material

### ISSUE THREAD

**Issue by swift502** [ucupumar/ucupaint#2]
Hi, it wouldn't be fun if I didn't find something. 😄

If objects in collections that are disabled for rendering share a material with the rendered object, I get baking errors.
The scene looks like this: A and C share a material. C is disabled for rendering. I want to bake A.

![image](https://user-images.githubusercontent.com/24359130/178116565-15751e9f-af4b-40c8-87f5-e19cf461e270.png)

This happens:

https://user-images.githubusercontent.com/24359130/178116610-d0d55d40-db61-4069-a00e-de092a995121.mp4

[Here's the blend file from the video](https://github.com/ucupumar/ucupaint/files/9077608/blend.file.zip)

I would personally love it if the behavior was the same as Blender's baking method.
Let me know what you think!

**Comment by ucupumar** [comment]
Ok, let me check it first

**Comment by ucupumar** [comment]
Hmm, I think you're right. I defaulted to unhide all objects that using the same material. Maybe it should be an option. And I just realized FXAA caused the baking process taking so long to finish, I think I will make it optional.

**Comment by swift502** [comment]
> I defaulted to unhide all objects that using the same material. Maybe it should be an option

Okay, yeah I would appreciate that.

I always keep a bunch of old versions of models for reference so some way to disable this would make my life easier, so I don't have to manually delete all the shared materials.

**Comment by ucupumar** [comment]
I see, this is not hard but still need a bit of time to implement, so please be patient. :)

**Comment by ucupumar** [comment]
Okay, I fixed it, no need for a special option to disable object hide render when baking since I didn't find any use case for it. Also, I kept FXAA on by default because it's not that slow when I use it again. :)

**Comment by swift502** [comment]
@ucupumar Awesome. 🙂

I didn't notice a major slowdown with FXAA yet. And it's a great feature, so I think it can be enabled by default.
