### ISSUE TITLE
Bake all layers,materials, viewport shadows and lightning as a single flat picture

### ISSUE THREAD

**Issue by Dereuz24** [ucupumar/ucupaint#203]
It would be useful to have an option in the bake menu to bake everything on viewport down into a single new image without having to set it up by hand every time while keeping the nodes just like the regular multichannel baking

https://www.youtube.com/watch?v=RQyAsi_Jvmc

**Comment by don570** [comment]
There is a method of baking the screen using Quick Edit and Ucupaint.
It requires setting up.
 https://www.youtube.com/watch?v=kqnF3LCm-cA

**Comment by Dereuz24** [comment]
> There is a method of baking the screen using Quick Edit and Ucupaint. It requires setting up. https://www.youtube.com/watch?v=kqnF3LCm-cA

Thanks! It works great when creating a new layer and targeting the quick bake directly to that selected layer in Ucupaint

Is there any way to do this for every angle in an automated way or does it has to be done by hand by moving the camera? The corners are problematic when captured from afar. With shortcuts is somehow fast but are there any scripts or built in shortcuts to just get everything around the objects at a fixed resolution?

**Comment by don570** [comment]
I believe that there are various blender add-ons that display explosion,s fire and smoke that allow camera movement,
but this is an area where I have no experience.
----------------------------------------------------------------------------------
I showed a material that would appear the same no matter what angle the camera is pointing.
I used the layer weight node.
https://www.youtube.com/watch?v=7EAZ3AE6cvU&t=18s

Discussion:
https://github.com/ucupumar/ucupaint/issues/176

**Comment by Dereuz24** [comment]
Sorry I didn't mean a billboard, camera facing material

I meant a way to do a quick edit, view/camera bake on every angle of the object. Automatically bake front back top bottom left and right in one go

When you click quick edit the texture is baked from the camera view and  then you have to repeat the process for every face of a cube for example

**Comment by don570** [comment]
Small correction.   Doesn't Quick Edit take the image from the screen point of view not the camera point of view??

So for a cube it would need  5 of the 6 faces to be taken.

Note with a cube  you can place all the faces on top of each other in the UV Layout process  --->   'Reset'
which is a trick that I like to do to reduce work.

**Comment by ucupumar** [comment]
Hmm, I don't think baking a fully shaded texture is fit for ucupaint since it's a channel-based node setup. I think there are plenty of other addons that can do it for you.

**Comment by Dereuz24** [comment]
> Hmm, I don't think baking a fully shaded texture is fit for ucupaint since it's a channel-based node setup. I think there are plenty of other addons that can do it for you.

Yes I see it now. I wanted it to behave like the multichannel baking with the swappable nodes but there's really no point in doing that if we can just bake to an arbitrary single image. 

I'll close this thanks
