### ISSUE TITLE
Adding a new vertex color mask resets the extension mode of a previous decal image mask back to clip

### ISSUE THREAD

**Issue by Dereuz24** [ucupumar/ucupaint#209]
Hi there,

I found that if you add a new image mask layer and then set the extension mode to repeat, every new subsequent mask layer after that resets the extension mode from repeat to clip instead of keeping the mode selected by the user at the beginning. 

In case you are having difficulties reproducing this, it happens every time with the decal mask plus the vertex color mask.

- New layer on a blank cube, solid or image layer
- New mask, source Decal
- Set extension to repeat
- New vertex color mask
- The addon automatically resets the extension of the image back to clip

**Comment by ucupumar** [comment]
Decal is designed to use clip extension, that's why it kept coming back to it. Is there any usecase for using decal with other than clip extension?

**Comment by Dereuz24** [comment]
> Decal is designed to use clip extension, that's why it kept coming back to it. Is there any usecase for using decal with other than clip extension?
> 
> I probably need to hide the extension option when decal is used

Controlling the rotation and scale of image texture masks with the empty widget is convenient. Sliders are ok but this allows the user to scale and rotate textures directly on viewport without going back to the side panel
