### ISSUE TITLE
Baked texture export error.

### ISSUE THREAD

**Issue by Sk3in** [ucupumar/ucupaint#210]
When I try to export the baked textures, I get this error. Any idea how to fix it? I'm in Blender 4.2.3 LTS

`Python: Traceback (most recent call last):
  File "C:\Users\Skein\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\blender_org\ucupaint\image_ops.py", line 706, in execute
    image.save_render(path, scene=tmpscene)
RuntimeError: Error: Image 'Ucupaint Material Color' does not have any image data`

![imagen_2024-10-22_232248349](https://github.com/user-attachments/assets/b141f4c8-b229-450a-9bf7-b15db14dd06a)

Thanks.

**Comment by Sk3in** [comment]
Thank you for replying.
I have created a new cube and only added the color channel with a texture. When I select the option to export all baked textures, I get this error.
[cid:7d63331b-56d2-4a63-8df7-020b6cae1b44]

Thanks again.

***@***.***>
Skein Evergarden

Graphics Design and 3D artist.

[https://app.ed.team/static/images/utils/firma/theme/pin-purple.png]Tarragona, España
________________________________
De: ucupumar ***@***.***>
Enviado: miércoles, 23 de octubre de 2024 10:46
Para: ucupumar/ucupaint ***@***.***>
Cc: Sk3in ***@***.***>; Author ***@***.***>
Asunto: Re: [ucupumar/ucupaint] Baked texture export error. (Issue #210)


The error can be sourced from many things. Can you reproduce the error again using a new file?

**Comment by ucupumar** [comment]
it worked out fine here, can you record the process of how you reproduce the error?

**Comment by don570** [comment]
Blender 4.2.3 LTS
[Easy Daedalus 6.3.93 (6.4 RC1)](https://forum.puppylinux.com/viewtopic.php?t=12851) 

I got a similar error message as Sk3in when baking a solid color with mask layer
It didn't matter if I packed mask image or not.
I took screen video to see the error message.

https://youtu.be/oCcOseuFCIo

**Comment by ucupumar** [comment]
Ok, I can reproduce this issue if the blend file isn't saved yet

**Comment by don570** [comment]
Checked you recent version and it everything worked.
