### ISSUE TITLE
Select Decal crash

### ISSUE THREAD

**Issue by don570** [ucupumar/ucupaint#221]
Blender 3.4.2 LTS
Friday ucupaint

I checked out Decal feature and experienced crash

-Open available image  -->  I opened an image from previous project that I probably didn't save??
-I selected 'Decal' layer type
-Then I clicked 'Select Decal Object'  button and ucupaint crash occurred
I made video to show crash -
https://youtu.be/wejRirXp_sM

**Comment by ucupumar** [comment]
That's not a crash, ucupaint just won't be visible if you select a non-materialable object. Empty can't have a material so the UI won't show up until you select the box again. This is just a current limitation of ucupaint.

**Comment by don570** [comment]
I checked again and the decal feature works well when I shift - click on surface to place the cursor position on the surface.
Then I go through the procedure and the decal places on the surface.
______________________________________

I wonder .  Wouldn't the decal feature be better if it required one (or more) faces to be selected.  Then Ucupaint would calculate the center of the face and place the decal there.

Blender does have several features that require faces to selected  for instance knife tool

```
Knife selection Shift-K
Activates the knife with another set of options so only selected faces are cut 

```
https://docs.blender.org/manual/en/2.81/modeling/meshes/editing/subdividing/knife.html

But there might be problem  with a sphere that was created  by subdividing a cube, since the selected face
would be distant from the surface of sphere.
