### ISSUE TITLE
Opening images to single layer with 'Add Mask' enabled is causing error

### ISSUE THREAD

**Issue by YoCG** [ucupumar/ucupaint#223]
Working in single image mode is fine but when checking Udim usage, an error occurs.

https://youtu.be/-v3FAQJX-Ok

**Comment by ucupumar** [comment]
I just tested it and yeah, it's a bug, I'll try to fix it

**Comment by ucupumar** [comment]
The error is not specific to UDIM masks. It will always happen when you add a mask while opening images from material. You can add the mask manually after opening the images to avoid errors until the bug is fixed.
