### ISSUE TITLE
Remove Background decal feature

### ISSUE THREAD

**Issue by don570** [ucupumar/ucupaint#227]
Remove Background decal feature
Ucupaint  recent version
Blender 4.2 LTS

I noticed that when creating a background image there is a vector option --> decal

When I tested it I noticed that it isn't useful as a decal (see image)

The image compares a regular decal with the background decal.
The background image does exist when I switch over  to the texture workspace.
So I would recommend removing the Background decal feature to avoid confusion.

![Screenshot(1)](https://github.com/user-attachments/assets/51908c29-b6a2-4e62-8f37-8b689685cb24)

**Comment by ucupumar** [comment]
That vector option is for the mask of the background layer, not for the background layer itself. Also background layer is deprecated and will be removed in future versions.
