### ISSUE TITLE
transparent shader paint?

### ISSUE THREAD

**Issue by Kubanis** [ucupumar/ucupaint#229]
Thank you for this amazing addon.
I need to paint on transparent material - that means "channel" with alpha 0.
For example I need to paint leaves on tree plane cards...
How can I achieve that with UCU paint? I was seraching on wiki and net, and haven't found an answer.

**Comment by don570** [comment]
If you put the characters  'color' in the name of file  I find that I can open it up from the hard drive with ucupaint.  I think 'color' it can be at the end or beginning of the name. Check it out.

**Comment by Kubanis** [comment]
> If you put the characters 'color' in the name of file I find that I can open it up from the hard drive with ucupaint. I think 'color' it can be at the end or beginning of the name. Check it out.

I don't undesrtand - don't you answering into "wrong" thread? I am asking how to make default material transparent and paint on it into layers with UCU paint.

**Comment by don570** [comment]
If you mean that you want ucupaint to paint  a region of an image so it's transparent,
this is possible...
https://youtu.be/IYcbBZFMQv0

**Comment by Kubanis** [comment]
> If you mean that you want ucupaint to paint a region of an image so it's transparent, this is possible... https://youtu.be/IYcbBZFMQv0

Thank you for that - but I need to do this - I recorded video as an explanation.

https://github.com/user-attachments/assets/bc29539c-567b-4c27-bd7f-6793fe61521c

**Comment by ucupumar** [comment]
You need to enable alpha on the main color channel, shown here in this tweet : https://x.com/ucupaint/status/1790353019877671383
If you need to create a cutout, you can use a background layer: https://x.com/ucupaint/status/1792134005548274044

Also it's explained In the wiki, https://ucupumar.github.io/ucupaint-wiki/01.01.channel/#rgb

Currently that's the way to use alpha in ucupaint, but there will be a refactor to make it less hidden and more flexible (#183), it will take a while for it to be implemented tho.

**Comment by don570** [comment]
I made a video showing how to paint on a transparent object
https://youtu.be/smLBeotJHKc

**Comment by Kubanis** [comment]
Thank you so much @don570 and @ucupumar ! You helped me a lot, sorry for such a basic question, I really couldn't do it.
Now I see how amazing is the UCUpaint! You actually fixed "dark edges" alpha problem - you are truly amazing.
