### ISSUE TITLE
Images get Packed after Saving them externally

### ISSUE THREAD

**Issue by trashmaster9000** [ucupumar/ucupaint#230]
Hi,
noticed some changed behaviour since the last update:
Baked textures also get packed if saved as image

Blender 4.3.2
Ucupaint 2.1.4

Steps to reproduce:
Add custom Bake target, do "Bake All Channels"
save Custom Bake target via "Save As Image"
Image gets Saved to choosen location and Packed into the blender file simultanously

**Comment by trashmaster9000** [comment]
thank you for the quick fix!

**Comment by trashmaster9000** [comment]
i think this change introduced a new bug :/
the images don't get saved automatically if the blender file gets saved

could you maybe have another look at it?

**Comment by ucupumar** [comment]
I don't think the code is related, maybe you can create a new issue about that one and step by step how to reproduce that since the issue does not happen here
