### ISSUE TITLE
Errors when repeatedly adding and removing the Ucupaint node

### ISSUE THREAD

**Issue by swift502** [ucupumar/ucupaint#5]
I bring you more bugs. 🙂

Windows 10
Ucupaint: 1.0.7
Blender: 3.3.0

### Steps to reproduce

1. Select any object (e.g. the default cube)
2. Do "Quick Ucupaint Node Setup" on it
3. Do "Remove Ucupaint node" from the ucupaint menu
4. Do "Quick Ucupaint Node Setup" again
5. Change settings in the "last action" menu
6. Get errors or even a crash

Video:

https://user-images.githubusercontent.com/24359130/190918102-d7360494-9f99-474c-b696-d4811babff8c.mp4

**Comment by ucupumar** [comment]
Thanks for the bug report. I already fixed it! 😀
