### ISSUE TITLE
"Toggle Eraser" button only works on brushes named "TexDraw" / "Draw" / "Paint"

### ISSUE THREAD

**Issue by kobligo** [ucupumar/ucupaint#57]
Ucupaint 1.1.0, Blender 3.6.5, Windows10

I would like to point out a general design flaw with the Toggle Eraser button.
As can be seen in the execute() function in vcol_editor.py starting at line 112, Toggle Eraser makes oddly specific assumptions about the user's brush data. In the case that the standard brush ("TexDraw" / "Draw" / "Paint") has been deleted or renamed, the Toggle Eraser button does nothing and pressing it often results in an error pop-up.

Perhaps simply toggling the blend mode of the active brush would be safer than trying to get references to specific brushes that may or may not exist, especially when done without a null check or any other kind of precaution.
The user will never understand what's wrong unless they look at the code.

**Comment by ucupumar** [comment]
Thanks for the report! I see, currently i can't access my pc so maybe you can create a pull request for fix so i can check it later.

**Comment by kobligo** [comment]
Turns out it's not as easy as I thought in terms of design. I do not understand your reasoning behind picking the "TexDraw" brush specifically, and I don't feel like I should mess with your "vision" for this Toggle button.

Was it part of your design that the player would always reserve the default TexDraw brush as a dedicated eraser?
If you want a dedicated Eraser brush, why not have the add-on create one on the fly and name it "Eraser" in case there isn't one?
Why don't we use the current brush as an eraser and just toggle its blend mode?
