### ISSUE TITLE
Icon missing

### ISSUE THREAD

**Issue by iillya** [ucupumar/ucupaint#66]
I don't know how to trigger this bug stably.Sometimes restarting the blender can solve the issue.
<img width="492" alt="Snipaste_2023-12-08_11-22-20" src="https://github.com/ucupumar/ucupaint/assets/112866800/d0f35497-dae3-46cc-a654-b78ddf575b87">

**Comment by ucupumar** [comment]
Yeah, sometimes blender fails to load custom icons. Try to reload the scripts using F3 and see if that solves your problem if that happens again.
![image](https://github.com/ucupumar/ucupaint/assets/5253453/b583d574-2d4f-49b0-9431-4d5a49db2c26)
