### ISSUE TITLE
Feature request: Can bake a channel onto a vertex color(Color Attribute)

### ISSUE THREAD

**Issue by morirain** [ucupumar/ucupaint#78]
I exported the model to the Unreal Engine and used the four channels of vertex color to control the material.
But it's hard for me to draw vertex alpha channels, which is a bit cumbersome.
If we can treat the vertex color as a texture, it will be easy to paint in Ucupaint, just do a little work on the final bake.

**Comment by ucupumar** [comment]
You can already do it if you're turned on experimental features. But I don't think it works with alpha yet
![image](https://github.com/ucupumar/ucupaint/assets/5253453/5cc493b0-85e4-4c40-9ffa-63614326ac0c)

**Comment by morirain** [comment]
Wow, that's good news, your work is amazing

**Comment by ucupumar** [comment]
@morirain Hey, thanks for the PR! I'm thinking about closing this issue if bake vertex color can become an option for bake all channels. So the bake result can be switched between vertex colors or texture, something like that. Feel free to propose something or even an implementation.

**Comment by morirain** [comment]
This is a good idea, perhaps need to add a vertex color channel type, or add an option “Bake as Vertex Color” for all channel types.

**Comment by ucupumar** [comment]
I'm not sure that I understand what you meant. Can you create a UI mockup of how will it behave?

**Comment by morirain** [comment]
![2024-01-07](https://github.com/ucupumar/ucupaint/assets/10196181/b6e194f6-28a8-46cc-80fc-7b7c50a1c80d)
I think the "**Bake all channels**" button should remain the same.
As shown, if I need to bake a channel into a vertex color, i can just turn on the option in the channel options.
If the channel also has the "**Base Alpha**" option turned on, the alpha will also be baked to the vertex color(may cause confusion?)

so the point is how to know the channel needs to be baked to the vertex color, and the preview of the vertex color.
for me I don't connect the vertex color channel to the material, I just open "**Preview mode**" to see if the color is correct, i will need to manually bake later to see the real vertex colors

**Comment by ucupumar** [comment]
Hmm, that can be a solution. So the baked channels can be mixtures of a texture or a vertex color? Is the option visible after using 'Use Baked'?

**Comment by morirain** [comment]
Vertex colors and maps should be separated, the resolution of vertex colors and maps can be very different depending on the polygon count, maybe there should be a separate "**Preview Vertex Color**" option if ”**Baked As Vertex Color**“ is enable? This allows you to see the actual vertex colors

**Comment by ucupumar** [comment]
So the map will also baked even when the 'Bake as vertex color' is enabled? Maybe you can prototype this already if you want. I can give feedback along the way.

**Comment by morirain** [comment]
> So the map will also baked even when the 'Bake as vertex color' is enabled? Maybe you can prototype this already if you want. I can give feedback along the way.

https://github.com/morirain/ucupaint/tree/bake_vertex_color
Check this branch, I didn't write any comments, nor did I check it carefully

**Comment by ucupumar** [comment]
Ok, maybe you can create another pull request for this, since easier to test and give the feedback that way.

**Comment by frkntlr** [comment]
Any progress on this issue? Addition or discarded clone.

**Comment by ucupumar** [comment]
> Any progress on this issue? Addition or discarded clone.

You can watch the progress on #83

**Comment by ucupumar** [comment]
@morirain I just replaced 'use_bake_as_vcol' with 'bake_target' enum property so the UI can also be usable for packed channels baking. Bake as vertex color can now be accessed here:
![image](https://github.com/ucupumar/ucupaint/assets/5253453/af188230-df8e-4cc1-ad7e-9bb8b19f7329)

I'm closing this issue now since the feature has already been implemented.
