### ISSUE TITLE
Feature request: Can add a textures generator like bpainter?

### ISSUE THREAD

**Issue by iillya** [ucupumar/ucupaint#8]
Feature request: Can add a textures generator like bpainter to make composite rgba channel more convenient ?
![image](https://user-images.githubusercontent.com/112866800/226241412-2bf5ac72-b9f2-41a2-94cf-6b7791045bd6.png)

**Comment by ucupumar** [comment]
Can you explain what does it do? I'm not familiar with bpainter.

**Comment by iillya** [comment]
> Can you explain what does it do? I'm not familiar with bpainter.
The functionality it implements is similar to combine color in compositor.But it can composite not only pictures, but also channels like this.

![Uploading image.png…]()

**Comment by iillya** [comment]
> Can you explain what does it do? I'm not familiar with bpainter.

The functionality it implements is similar to combine color in compositor.But it can composite not only pictures, but also channels like this.
![image](https://user-images.githubusercontent.com/112866800/226267709-f32102c5-2896-4886-8862-da5148608f06.png)

**Comment by ucupumar** [comment]
I see. Do you want the baked channels to be filled in the RGB channel of a single texture, something like that?

**Comment by iillya** [comment]
> I see. Do you want the baked channels to be filled in the RGB channel of a single texture, something like that?

YES

**Comment by ucupumar** [comment]
I actually think about this feature before, but I'm not sure how to integrate a UI that makes sense in ucupaint. Do you have an idea or proposal for how to do it?

**Comment by iillya** [comment]
> I actually think about this feature before, but I'm not sure how to integrate a UI that makes sense in ucupaint. Do you have an idea or proposal for how the UI will work?

OK.I will have a try.

**Comment by iillya** [comment]
> I actually think about this feature before, but I'm not sure how to integrate a UI that makes sense in ucupaint. Do you have an idea or proposal for how the UI will work?

I think you can refer to the logic of another plugin Philogix PBR Painter.I modified it slightly
![ui](https://user-images.githubusercontent.com/112866800/226547690-399965fd-fb54-4e4c-8ae0-f7173dccd099.png)

**Comment by ucupumar** [comment]
Hmm, I think it's too complicated to add another panel specific to this. I prefer if the panel will be on the channel settings instead. After some more thinking, it's probably more compact if the option is just a checkbox to export the channel as one bundled texture. And the RGBA order will be the same as the order of the channels. Something like that. What do you think?

**Comment by iillya** [comment]
> Hmm, I think it's too complicated to add another panel specific only for this. I prefer if the panel will be on the channel settings instead. After some more thinking, it's probably more compact if the option is just a checkbox to export the channel as one bundled texture. And the RGBA order will be the same as the order of the channels. Something like that. What do you think?

I prefer to manually check the export to a certain channel.Something like this.How about it？
![ui](https://user-images.githubusercontent.com/112866800/226935027-6c3f65a5-9dea-42bc-ab25-a757e89b92a0.png)

**Comment by ucupumar** [comment]
Hmm, the problem with this approach is I need to set the image first to use its RGB channels. How to make it automatically assign to the B channel of the newly generated image after baking? 

I want more automatization because some applications like godot can read ORM textures, it will be cumbersome to manually create a new image and assign the RGB target for each channel for every material.

**Comment by ucupumar** [comment]
Update on this issue, I actually already started the implementation a few months ago, but I guess I forced the automation too much so it made the implementation very messy, I think I'll start from scratch instead. I think the manual checkbox will be a better option I guess. So the ORM, or any other can be chosen as preset if all the channels are available.

**Comment by ucupumar** [comment]
I just committed a base implementation of channel packing/custom bake target in ucupaint. It can be accessed here:
![image](https://github.com/ucupumar/ucupaint/assets/5253453/3a07f4a9-a558-4b52-bd1e-7cd36900bf7c)
I still need to add a simpler UI element to show the name of the baked images.

**Comment by ucupumar** [comment]
I just added a new menu to save and pack the image results. I also added presets to create GLTF ORM and DirectX normal bake targets. Feel free to add more preset suggestion before I close this issue.

**Comment by ZAQraven** [comment]
Suggestion: Each channel should be added to adjust the value of color such as color ramp.

**Comment by ucupumar** [comment]
> Suggestion: Each channel should be added to adjust the value of color such as color ramp.

Thanks for the suggestion, but currently there's no way to preview the bake target so there's no way to preview the color adjustment. For the initial implementation, this is just for packing the channel results into a single texture. There will probably be a dedicated preview mode for custom bake targets in the future, but it's not covered in this issue,

Since there are no more preset suggestions, I think I'm closing this issue now.
