### ISSUE TITLE
Add "Save All" button

### ISSUE THREAD

**Issue by trashmaster9000** [ucupumar/ucupaint#88]
hello!

just discovered this addon, absolutely love it!
thank you for your awesome work!

what i'm missing is a easy to reach "Save All Images" button, maybe below the layer list?
would be nice if that could be added

**Comment by ucupumar** [comment]
Thank you! I think it's possible to add it in ucupaint, but you can also use blender's built-in unpack resources for that.
![image](https://github.com/ucupumar/ucupaint/assets/5253453/740fd240-8b62-4baf-891d-b24ac4469e7e)

**Comment by trashmaster9000** [comment]
sorry, i was maybe not clear enough

if i change a layer there is "*" displayed after the layer Name, i have to go through the menu to save each layer to disk manually.
would be nice if there was a button under the layer list to save all changed layers to their image files (and if they are not saved externally pack them into the blender file)

blender had this feature before 4.0 but not anymore

**Comment by ucupumar** [comment]
Ohh, it's already done automatically. When you save the blend file, ucupaint will also save all the layer images and masks.

**Comment by trashmaster9000** [comment]
ah, good to know!

havnt noticed that, i'm not saving my blend file when i'm only painting on images, i just save those

**Comment by ucupumar** [comment]
I don't think save all button is needed in ucupaint, since saving is already automatic. Closing this issue
