### ISSUE TITLE
what I baked is not the same as what I preview.

### ISSUE THREAD

**Issue by iillya** [ucupumar/ucupaint#9]
What I baked is not the same as what I preview.It seems to bake the content of other channels.I can't find the reason.
<img width="1937" alt="Snipaste_2023-03-30_12-27-40" src="https://user-images.githubusercontent.com/112866800/228730326-988e1c5c-1a63-4639-b5bb-1ba8a71548a5.png">
<img width="1643" alt="Snipaste_2023-03-30_12-28-07" src="https://user-images.githubusercontent.com/112866800/228730337-4cd1aa21-134e-4f36-b6a3-cd0a33e7915e.png">

blender 3.4.1
addon 1.0.12
blender file
[untitled.zip](https://github.com/ucupumar/ucupaint/files/11107778/untitled.zip)

**Comment by ucupumar** [comment]
Sorry for the late response, I didn't get a notification for this issue for some reason. I just checked your file, are you ever editing the inside of ucupaint node?

**Comment by ucupumar** [comment]
I'm not sure what happened to your ucupaint node but some channels use the same baked image target node. It's not supposed to happen, but I already committed a change to make sure every channel uses a unique baked node. 
Please use the master version of ucupaint and rebake the channels again.
